/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Result */
        get: operations["get_job_result_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/runs/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Job Run */
        post: operations["submit_job_run_jobs_runs_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Job */
        post: operations["review_job_jobs__job_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{job_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Spec */
        get: operations["get_workflow_spec_workflows__job_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["list_prompts_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["get_prompt_prompts__name__get"];
        /** Update Prompt */
        put: operations["update_prompt_prompts__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt-executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_prompt_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompt-executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_prompt_executions__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifact Types */
        get: operations["list_artifact_types_artifacts_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emit Log */
        post: operations["emit_log_jobs__job_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Logs */
        get: operations["stream_logs_jobs__job_id__logs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/math-conversation/event-types/crew-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CrewChatEvent schema (for client codegen)
         * @description Return a representative CrewChatEvent so the OpenAPI schema
         *     carries the type and `gen:api` picks it up for typed FE
         *     parsing. Not for live consumption — live events flow over
         *     `/jobs/{id}/logs/stream` and are detected by JSON-parsing each
         *     log line and matching the `event` discriminator.
         */
        get: operations["get_crew_chat_event_schema_math_conversation_event_types_crew_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactListResponse */
        ArtifactListResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ArtifactSummary
         * @description Lightweight row for the artifact list view — enough to render
         *     the index and filter without hydrating every full artifact.
         */
        ArtifactSummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Type */
            artifact_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Job */
            created_by_job?: string | null;
        };
        /** ArtifactTypeListResponse */
        ArtifactTypeListResponse: {
            /** Artifact Types */
            artifact_types: components["schemas"]["ArtifactTypeSpec"][];
        };
        /**
         * ArtifactTypeSpec
         * @description One registered artifact type — `BaseArtifact` subclass projected
         *     into a UI-friendly registry entry. Drives the `/artifact-types`
         *     viewer.
         */
        ArtifactTypeSpec: {
            /** Artifact Type */
            artifact_type: string;
            /** Class Name */
            class_name: string;
            /** Domain */
            domain?: string | null;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["ParamSpec"][];
        };
        /**
         * ConversationTurn
         * @description A single agent move in the conversation.
         *
         *     Embedded in `MathConversationArtifact.turns` and mirrored on
         *     `MathConversationState.turns` while the run is in flight. `latex`
         *     and `figure` are inline — the math-ui `<Latex>` component and figure
         *     renderer take these values directly.
         */
        ConversationTurn: {
            /** Turn Index */
            turn_index: number;
            /** Agent Role */
            agent_role: string;
            /** Agent Persona */
            agent_persona: string;
            /** Content */
            content: string;
            /** Latex */
            latex?: string | null;
            /** Figure */
            figure?: {
                [key: string]: unknown;
            } | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRecord"][];
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
        };
        /**
         * CrewChatEvent
         * @description One event in the live conversation stream.
         *
         *     Mirrors `docs/math_conversation.md` → Live visibility. Optional
         *     fields are populated per event kind (e.g. `content` on `message`,
         *     `tool_name` on `tool_call`).
         */
        CrewChatEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "signed_in" | "is_typing" | "message" | "tool_call" | "tool_result" | "concluded" | "signed_out" | "status";
            /** Agent Role */
            agent_role?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Turn Index */
            turn_index?: number | null;
            /** Content */
            content?: string | null;
            /** Latex */
            latex?: string | null;
            /** Tool Name */
            tool_name?: string | null;
            /**
             * Elapsed Seconds
             * @default 0
             */
            elapsed_seconds: number;
            /** Turns Used */
            turns_used?: number | null;
            /** Turns Budget */
            turns_budget?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
        };
        /** EdgeResponse */
        EdgeResponse: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
        };
        /**
         * FigureArtifact
         * @description Validated semantic figure spec (Munkres / Lee / Tu style).
         *
         *     Produced by `RenderFigureStep` after the agent has converged on
         *     a structurally valid spec via the `validate_figure` tool. The
         *     `spec` is an opaque JSON payload — the FEATURES.md plan calls
         *     for keeping it as `dict[str, Any]` server-side; the renderer
         *     contract lives in `math-ui`. `template` is duplicated out of the
         *     spec for indexable filtering.
         */
        FigureArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "figure";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /**
             * Template
             * @description Top-level template name (also at spec['template']).
             */
            template: string;
            /**
             * Spec
             * @description The validated semantic figure spec — opaque JSON.
             */
            spec: {
                [key: string]: unknown;
            };
            /**
             * Validation Attempts
             * @default 1
             */
            validation_attempts: number;
        };
        /**
         * GateSpec
         * @description Execution-policy gate — declares that after `node_name` runs,
         *     a human review of `review_type` must be submitted before the
         *     workflow continues.
         */
        GateSpec: {
            /** Node Name */
            node_name: string;
            /** Review Type */
            review_type: string;
            /**
             * Params
             * @default []
             */
            params: components["schemas"]["ParamSpec"][];
        };
        /** GeneratedAnswerArtifact */
        GeneratedAnswerArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "ai_answer";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /** Answer Text */
            answer_text: string;
            /** Reasoning Steps */
            reasoning_steps?: string[];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Model Used */
            model_used?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResultResponse */
        JobResultResponse: {
            /** Job Id */
            job_id: string;
            /** Result */
            result?: (components["schemas"]["MathQAResult"] | components["schemas"]["MathConversationResult"]) | null;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Stage */
            stage?: string | null;
            /** Percent */
            percent?: number | null;
            /** Message */
            message?: string | null;
            /** Waiting For */
            waiting_for?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Result */
            result?: (components["schemas"]["MathQAResult"] | components["schemas"]["MathConversationResult"]) | null;
        };
        /**
         * LatexAnswerArtifact
         * @description Validated LaTeX rendering of an AI answer.
         *
         *     Produced by `GenerateLatexStep` after the agent has converged on
         *     KaTeX-compilable source via the `validate_latex` tool. `is_valid`
         *     is always True at persistence time — invalid drafts never escape
         *     the validation loop. `validation_attempts` records how many
         *     rounds of tool feedback the agent took to converge.
         */
        LatexAnswerArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "latex_answer";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /**
             * Latex Source
             * @description KaTeX-compilable LaTeX body.
             */
            latex_source: string;
            /**
             * Is Valid
             * @default true
             */
            is_valid: boolean;
            /**
             * Validation Attempts
             * @default 1
             */
            validation_attempts: number;
        };
        /**
         * LogEntry
         * @description Single log record emitted by the worker for one job.
         */
        LogEntry: {
            /** Job Id */
            job_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Level
             * @default info
             * @enum {string}
             */
            level: "info" | "warning" | "error" | "debug";
            /** Message */
            message: string;
            /** Stage */
            stage?: string | null;
            /** Source */
            source?: string | null;
        };
        /**
         * MathConversationArtifact
         * @description The whole brainstorm transcript, persisted once at end-of-run.
         *
         *     `seed_question` is the question the panel explored — pulled from a
         *     source `math_qa` job's artifacts or wrapped from fresh input text.
         *     `source_job_id` records provenance when seeded from a prior job.
         */
        MathConversationArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "math_conversation";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /** Source Job Id */
            source_job_id?: string | null;
            /** Seed Question */
            seed_question: string;
            /** Turns */
            turns?: components["schemas"]["ConversationTurn"][];
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /**
             * Stop Reason
             * @default max_turns
             * @enum {string}
             */
            stop_reason: "max_turns" | "concluded";
        };
        /**
         * MathConversationInput
         * @description Typed submit input — a variant of the platform request union.
         *
         *     Exactly one of `source_job_id` (seed from a completed `math_qa` job)
         *     or `question_text` (fresh question) must be set; the validator
         *     rejects "both" and "neither" at the API boundary.
         */
        MathConversationInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            job_type: "math_conversation";
            /**
             * Source Job Id
             * @description Seed from a completed math_qa job's artifacts.
             */
            source_job_id?: string | null;
            /**
             * Question Text
             * @description Fresh question to brainstorm (when not seeding from a job).
             */
            question_text?: string | null;
            /**
             * Max Turns
             * @description Hard cap on conversation turns.
             * @default 12
             */
            max_turns: number;
            /**
             * Created By
             * @description Submitting user.
             */
            created_by?: string | null;
        };
        /**
         * MathConversationResult
         * @description Typed result — a variant of the platform result union.
         *
         *     The single `conversation` artifact is resolved from `artifact_refs`
         *     by the result endpoint's hydrator.
         */
        MathConversationResult: {
            /** Artifact Refs */
            artifact_refs?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            job_type: "math_conversation";
            conversation?: components["schemas"]["MathConversationArtifact"] | null;
        };
        /**
         * MathQAInput
         * @description Typed submit input for a Math Q&A job — variant of the platform request union.
         */
        MathQAInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            job_type: "math_qa";
            /**
             * Question Text
             * @description The math question.
             */
            question_text: string;
            /**
             * Topic
             * @description E.g. algebra, calculus.
             */
            topic?: string | null;
            /**
             * Created By
             * @description Submitting user.
             */
            created_by?: string | null;
        };
        /**
         * MathQAResult
         * @description Typed result for a Math Q&A job — variant of the platform result union.
         *
         *     Each typed field is an artifact resolved from `artifact_refs` (defined
         *     on `BaseJobResult`). The result endpoint hydrates them via the
         *     workspace artifact store.
         */
        MathQAResult: {
            /** Artifact Refs */
            artifact_refs?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            job_type: "math_qa";
            question?: components["schemas"]["MathQuestionArtifact"] | null;
            ai_response?: components["schemas"]["GeneratedAnswerArtifact"] | null;
            latex?: components["schemas"]["LatexAnswerArtifact"] | null;
            figure?: components["schemas"]["FigureArtifact"] | null;
            review?: components["schemas"]["UserCommentArtifact"] | null;
        };
        /** MathQuestionArtifact */
        MathQuestionArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "math_question";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /** Question Text */
            question_text: string;
            /** Topic */
            topic?: string | null;
            /** Difficulty */
            difficulty?: string | null;
        };
        /** ParamSpec */
        ParamSpec: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** PromptExecutionListResponse */
        PromptExecutionListResponse: {
            /** Executions */
            executions: components["schemas"]["PromptExecutionSummary"][];
            /** Total */
            total: number;
        };
        /** PromptExecutionResponse */
        PromptExecutionResponse: {
            /** Id */
            id: string;
            /** Prompt Name */
            prompt_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input Data */
            input_data: {
                [key: string]: unknown;
            };
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Model Name */
            model_name?: string | null;
            /** Output Type */
            output_type?: string | null;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            } | null;
        };
        /** PromptExecutionSummary */
        PromptExecutionSummary: {
            /** Id */
            id: string;
            /** Prompt Name */
            prompt_name: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Model Name */
            model_name?: string | null;
        };
        /** PromptListResponse */
        PromptListResponse: {
            /** Prompts */
            prompts: components["schemas"]["PromptResponse"][];
            /** Total */
            total: number;
        };
        /** PromptResponse */
        PromptResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Description */
            description: string;
            /** Instructions */
            instructions: string;
            /** Version */
            version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PromptUpdateRequest */
        PromptUpdateRequest: {
            /** Instructions */
            instructions?: string | null;
        };
        /** RootModel[Annotated[Union[MathQAInput, MathConversationInput], FieldInfo(annotation=NoneType, required=True, discriminator='job_type')]] */
        RootModel_Annotated_Union_MathQAInput__MathConversationInput___FieldInfo_annotation_NoneType__required_True__discriminator__job_type____: components["schemas"]["MathQAInput"] | components["schemas"]["MathConversationInput"];
        /** RunSubmitResponse */
        RunSubmitResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** StageResponse */
        StageResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /**
             * Is Human Step
             * @default false
             */
            is_human_step: boolean;
            /**
             * Resume Params
             * @default []
             */
            resume_params: components["schemas"]["ParamSpec"][];
        };
        /**
         * ToolCallRecord
         * @description One tool invocation an agent made inside a turn.
         */
        ToolCallRecord: {
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Result */
            result?: string | null;
        };
        /**
         * UserComment
         * @description User feedback on an AI response.
         */
        UserComment: {
            /** Comment Text */
            comment_text: string;
            /**
             * Rating
             * @description 1-5 star rating.
             */
            rating?: number | null;
            /**
             * Is Correct
             * @description Did the user mark the answer correct?
             */
            is_correct?: boolean | null;
        };
        /** UserCommentArtifact */
        UserCommentArtifact: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            artifact_type: "user_comment";
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By Job */
            created_by_job?: string | null;
            /** Comment Text */
            comment_text: string;
            /** Rating */
            rating?: number | null;
            /** Is Correct */
            is_correct?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowListItem
         * @description Lightweight registry entry — drives the platform-level workflow index.
         */
        WorkflowListItem: {
            /** Job Type */
            job_type: string;
            /** Label */
            label: string;
        };
        /** WorkflowListResponse */
        WorkflowListResponse: {
            /** Workflows */
            workflows: components["schemas"]["WorkflowListItem"][];
        };
        /** WorkflowSpecResponse */
        WorkflowSpecResponse: {
            /** Job Type */
            job_type: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Submit Params
             * @default []
             */
            submit_params: components["schemas"]["ParamSpec"][];
            /** Stages */
            stages: components["schemas"]["StageResponse"][];
            /** Edges */
            edges: components["schemas"]["EdgeResponse"][];
            /**
             * Gates
             * @default []
             */
            gates: components["schemas"]["GateSpec"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaArtifactListResponse = components['schemas']['ArtifactListResponse'];
export type SchemaArtifactSummary = components['schemas']['ArtifactSummary'];
export type SchemaArtifactTypeListResponse = components['schemas']['ArtifactTypeListResponse'];
export type SchemaArtifactTypeSpec = components['schemas']['ArtifactTypeSpec'];
export type SchemaConversationTurn = components['schemas']['ConversationTurn'];
export type SchemaCrewChatEvent = components['schemas']['CrewChatEvent'];
export type SchemaEdgeResponse = components['schemas']['EdgeResponse'];
export type SchemaFigureArtifact = components['schemas']['FigureArtifact'];
export type SchemaGateSpec = components['schemas']['GateSpec'];
export type SchemaGeneratedAnswerArtifact = components['schemas']['GeneratedAnswerArtifact'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaJobResultResponse = components['schemas']['JobResultResponse'];
export type SchemaJobStatusResponse = components['schemas']['JobStatusResponse'];
export type SchemaLatexAnswerArtifact = components['schemas']['LatexAnswerArtifact'];
export type SchemaLogEntry = components['schemas']['LogEntry'];
export type SchemaMathConversationArtifact = components['schemas']['MathConversationArtifact'];
export type SchemaMathConversationInput = components['schemas']['MathConversationInput'];
export type SchemaMathConversationResult = components['schemas']['MathConversationResult'];
export type SchemaMathQaInput = components['schemas']['MathQAInput'];
export type SchemaMathQaResult = components['schemas']['MathQAResult'];
export type SchemaMathQuestionArtifact = components['schemas']['MathQuestionArtifact'];
export type SchemaParamSpec = components['schemas']['ParamSpec'];
export type SchemaPromptExecutionListResponse = components['schemas']['PromptExecutionListResponse'];
export type SchemaPromptExecutionResponse = components['schemas']['PromptExecutionResponse'];
export type SchemaPromptExecutionSummary = components['schemas']['PromptExecutionSummary'];
export type SchemaPromptListResponse = components['schemas']['PromptListResponse'];
export type SchemaPromptResponse = components['schemas']['PromptResponse'];
export type SchemaPromptUpdateRequest = components['schemas']['PromptUpdateRequest'];
export type SchemaRootModelAnnotatedUnionMathQaInputMathConversationInputFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorJobType = components['schemas']['RootModel_Annotated_Union_MathQAInput__MathConversationInput___FieldInfo_annotation_NoneType__required_True__discriminator__job_type____'];
export type SchemaRunSubmitResponse = components['schemas']['RunSubmitResponse'];
export type SchemaStageResponse = components['schemas']['StageResponse'];
export type SchemaToolCallRecord = components['schemas']['ToolCallRecord'];
export type SchemaUserComment = components['schemas']['UserComment'];
export type SchemaUserCommentArtifact = components['schemas']['UserCommentArtifact'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaWorkflowListItem = components['schemas']['WorkflowListItem'];
export type SchemaWorkflowListResponse = components['schemas']['WorkflowListResponse'];
export type SchemaWorkflowSpecResponse = components['schemas']['WorkflowSpecResponse'];
export type $defs = Record<string, never>;
export interface operations {
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_result_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                job_type?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_run_jobs_runs_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RootModel_Annotated_Union_MathQAInput__MathConversationInput___FieldInfo_annotation_NoneType__required_True__discriminator__job_type____"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_job_jobs__job_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserComment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
        };
    };
    get_workflow_spec_workflows__job_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_prompts_get: {
        parameters: {
            query?: {
                domain?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_prompts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_prompts__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_prompt_executions_get: {
        parameters: {
            query?: {
                prompt_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptExecutionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_prompt_executions__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifact_types_artifacts_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTypeListResponse"];
                };
            };
        };
    };
    list_artifacts_artifacts_get: {
        parameters: {
            query?: {
                /** @description Filter by `created_by_job`. */
                job_id?: string | null;
                /** @description Filter by discriminator. */
                artifact_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathQuestionArtifact"] | components["schemas"]["GeneratedAnswerArtifact"] | components["schemas"]["UserCommentArtifact"] | components["schemas"]["LatexAnswerArtifact"] | components["schemas"]["FigureArtifact"] | components["schemas"]["MathConversationArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emit_log_jobs__job_id__logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_logs_jobs__job_id__logs_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crew_chat_event_schema_math_conversation_event_types_crew_chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrewChatEvent"];
                };
            };
        };
    };
}
